[package]
name = "bpf-adder"
version = "0.1.0"
authors = ["alex", "bigpep"]
edition = "2021"

[dependencies]
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }

[lib]
name = "flipper"
path = "lib.rs"
crate-type = [
	"cdylib",
]
